-- Seed data for CocoWeb (select database before running if needed)
TRUNCATE users;
TRUNCATE guestbook;

INSERT INTO users (username, password, email) VALUES
('admin', 'password', 'admin@example.local'),
('guest', 'guest', 'guest@example.local'),
('alice', 'alice', 'alice@example.local'),
('bob', 'bob', 'bob@example.local'),
('charlie', 'charlie', 'charlie@example.local'),
('diana', 'diana', 'diana@example.local'),
('eve', 'eve', 'eve@example.local'),
('frank', 'frank', 'frank@example.local'),
('grace', 'grace', 'grace@example.local'),
('heidi', 'heidi', 'heidi@example.local'),
('ivan', 'ivan', 'ivan@example.local'),
('judy', 'judy', 'judy@example.local'),
('mallory', 'mallory', 'mallory@example.local'),
('oscar', 'oscar', 'oscar@example.local'),
('peggy', 'peggy', 'peggy@example.local'),
('trent', 'trent', 'trent@example.local'),
('victor', 'victor', 'victor@example.local'),
('walter', 'walter', 'walter@example.local'),
('sybil', 'sybil', 'sybil@example.local'),
('nina', 'nina', 'nina@example.local'),
('quentin', 'quentin', 'quentin@example.local'),
('ruth', 'ruth', 'ruth@example.local'),
('sam', 'sam', 'sam@example.local'),
('tina', 'tina', 'tina@example.local'),
('ursula', 'ursula', 'ursula@example.local'),
('wendy', 'wendy', 'wendy@example.local'),
('xander', 'xander', 'xander@example.local'),
('yasmine', 'yasmine', 'yasmine@example.local'),
('zach', 'zach', 'zach@example.local'),
('developer', 'developer', 'dev@example.local');

INSERT INTO guestbook (name, message) VALUES
('system', 'Welcome to the guestbook.'),
('trainer', 'Switch security levels to observe behavior changes.'),
('alice', 'First post from Alice.'),
('bob', 'Testing stored messages.'),
('charlie', 'Remember to use localhost only.'),
('diana', 'Security is a spectrum.'),
('eve', 'Payloads live here.'),
('frank', 'Try different input encodings.'),
('grace', 'High mode should be safer.'),
('heidi', 'Keep data local.'),
('ivan', 'SQLi behaves differently by level.'),
('judy', 'XSS stored demo entry.'),
('mallory', 'Watch the output encoding.'),
('oscar', 'Reflected XSS is fun.'),
('peggy', 'Try unions on low.'),
('trent', 'Do not expose this lab.'),
('victor', 'Seed data is for practice.'),
('walter', 'Check SSRF restrictions.'),
('sybil', 'CSRF needs tokens.'),
('nina', 'Another simple guestbook entry.');
